workflows:
  android-build:
    name: Build Android App
    max_build_duration: 60
    environment:
      vars:
        BUILDOZER_SPEC_FILE: "buildozer.spec"
      groups:
        - google_credentials # Προαιρετικό αν ανεβάζεις στο Google Play
    scripts:
      - name: Install dependencies
        script: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython virtualenv
      
      - name: Initialize Buildozer (αν το αρχείο λείπει)
        script: |
          source venv/bin/activate
          if [ ! -f "buildozer.spec" ]; then
            buildozer init
          fi
      
      - name: Build APK
        script: |
          source venv/bin/activate
          buildozer android debug
    artifacts:
      - bin/*.apk
    publishing:
      email:
        recipients:
          - "panosgiannoulis76@gmail.com"
