workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        BUILDOZER_WARN_ON_ROOT: "0"
    scripts:
      - name: Install Python 3.11 & dependencies
        script: |
          pyenv install 3.11.6 --skip-existing
          pyenv global 3.11.6
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools
          pip install buildozer cython virtualenv

      - name: Install system dependencies
        script: |
          brew install openjdk@17
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          brew install zip unzip

      - name: Initialize Buildozer
        script: |
          source venv/bin/activate
          if [ ! -f "buildozer.spec" ]; then
            echo "Το αρχείο buildozer.spec δεν υπάρχει! Το δημιουργούμε..."
            buildozer init
          else
            echo "Το αρχείο buildozer.spec υπάρχει ήδη!"
          fi

      - name: Build APK
        script: |
          source venv/bin/activate
          buildozer android debug

    artifacts:
      - "bin/*.apk"

    publishing:
      email:
        recipients:
          - "panosgiannoulis76@gmail.com"
