workflows:
  android-build:
    name: Build Android App
    max_build_duration: 60
    environment:
      vars:
        BUILDOZER_WARN_ON_ROOT: "0"
      groups:
        - google_credentials # Προαιρετικό αν χρησιμοποιείς Google Play
    scripts:
      - name: Install dependencies
        script: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer cython virtualenv
      - name: Build APK
        script: |
          source venv/bin/activate
          buildozer android debug
    artifacts:
      - build/*.apk
    publishing:
      email:
        recipients:
          - "panosgiannoulis76@gmail.com"
